EFoF/Release_BACKEND

src/main/java/com/service/releasenote/domain/release/api/ReleaseController.java
src/main/java/com/service/releasenote/domain/release/application/ReleaseService.java
src/main/java/com/service/releasenote/domain/release/dto/ReleaseDto.java

+ 타이틀을 작성해주세요
***
+ YY.MM.DD
***

Revert "릴리즈 조회 로직 (DTO 변환) 수정"

---

src/main/java/com/service/releasenote/domain/company/dto/CompanyDTO.java
src/main/java/com/service/releasenote/domain/project/api/ProjectController.java
src/main/java/com/service/releasenote/domain/project/application/ProjectService.java
src/main/java/com/service/releasenote/global/config/JpaAuditConfiguration.java

오류 삭제 혹은 주석처리
***
23.07.18
***
민경 철웅 구현 부분 오류 삭제 혹은 주석처리

[REFACTOR] 민경철웅 부분 오류 수정

---

src/test/java/com/service/releasenote/IntegrationTest.java

+ 테스트 코드 인증 관련 문제 직면, 해결 중
***
+ 23.08.08
***
+ 테스트 코드 인증 관련 문제 직면
+ 로그인 이후 SecurityContext에 값이 할당되지 않고 자꾸만 비어있는 경우가 발생

테스트 코드 인증 관련 문제 직면, 해결 중

---

build.gradle
src/main/java/com/service/releasenote/ReleaseBackendApplication.java
src/main/java/com/service/releasenote/domain/company/api/CompanyController.java
src/main/java/com/service/releasenote/domain/company/application/CompanyService.java
src/main/java/com/service/releasenote/domain/company/dto/CompanyDTO.java
src/main/java/com/service/releasenote/domain/member/dto/MemberCompanyDTO.java
src/main/java/com/service/releasenote/global/config/S3Config.java
src/main/java/com/service/releasenote/global/config/S3Constants.java

[ADD&REFACTOR] s3 추가, Company 수정
***
23.08.08
***
s3 설정 추가 및 company 변수명 수정 등등

[ADD&REFACTOR] s3 추가, Company 수정

---

src/test/java/com/service/releasenote/IntegrationTest.java

+ 통합 테스트 일시정지
***
+ 23.08.08
***
+ 통합 테스트 일시정지
+ 현재 사용자 정보 관련 HOTFIX를 위한 조치

통합 테스트 일시정지

---

src/main/java/com/service/releasenote/domain/alarm/api/AlarmController.java
src/main/java/com/service/releasenote/domain/alarm/application/AlarmService.java
src/main/java/com/service/releasenote/domain/category/api/CategoryController.java
src/main/java/com/service/releasenote/domain/category/application/CategoryService.java
src/main/java/com/service/releasenote/domain/member/api/AuthController.java
src/main/java/com/service/releasenote/domain/member/api/MemberCompanyController.java
src/main/java/com/service/releasenote/domain/member/api/MemberProjectController.java
src/main/java/com/service/releasenote/domain/member/application/AuthService.java
src/main/java/com/service/releasenote/domain/member/application/MemberCompanyService.java
src/main/java/com/service/releasenote/domain/member/application/MemberProjectService.java
src/main/java/com/service/releasenote/domain/project/api/ProjectController.java
src/main/java/com/service/releasenote/domain/project/application/ProjectService.java
src/main/java/com/service/releasenote/domain/release/api/ReleaseController.java
src/main/java/com/service/releasenote/domain/release/application/ReleaseService.java
src/test/java/com/service/releasenote/IntegrationTest.java
src/test/java/com/service/releasenote/alarm/AlarmControllerTest.java
src/test/java/com/service/releasenote/alarm/AlarmServiceTest.java
src/test/java/com/service/releasenote/auth/AuthControllerTest.java
src/test/java/com/service/releasenote/auth/AuthServiceTest.java
src/test/java/com/service/releasenote/category/CategoryControllerTest.java
src/test/java/com/service/releasenote/category/CategoryServiceTest.java
src/test/java/com/service/releasenote/memberProject/memberProjectControllerTest.java
src/test/java/com/service/releasenote/memberProject/memberProjectServiceTest.java
src/test/java/com/service/releasenote/project/ProjectControllerTest.java
src/test/java/com/service/releasenote/project/ProjectServiceTest.java
src/test/java/com/service/releasenote/releases/ReleaseControllerTest.java
src/test/java/com/service/releasenote/releases/ReleaseServiceTest.java

+ 현재 사용자 관련 핫픽스, 테스트 코드 수정
***
+ 23.08.09
***
+ 모든 도메인에 대해 현재 사용자 관련 로직 수정
+ 수정에 따른 테스트 코드 변경, 정상화

현재 사용자 관련 핫픽스, 테스트 코드 수정

---

src/main/java/com/service/releasenote/domain/company/application/CompanyService.java
src/main/java/com/service/releasenote/global/config/S3Config.java
src/main/java/com/service/releasenote/global/constants/S3Constants.java

[REFACTOR] constants 경로 추가
***
23.08.09
***
s3 constants 경로 수정

[REFACTOR] constants 경로 추가

---

src/test/java/com/service/releasenote/IntegrationTest.java

+ 통합 테스트 공통 데이터 구성 완료
***
+ 23.08.09
***
+ 통합 테스트 공통 데이터 구성 완료

통합 테스트 공통 데이터 구성 완료

---

src/main/java/com/service/releasenote/global/config/SecurityConfig.java
src/main/java/com/service/releasenote/global/config/WebConfig.java
src/main/java/com/service/releasenote/global/error/handler/GlobalExceptionHandler.java

+ CORS 설정 추가 및 Header 에서 Token 확인 추가
***
+ 23.08.10
***
+ Cors 설정 추가
+ Header 에서 "Authorization" 을 키 값으로 가지는 Token 값 확인 불가 하였는데 수정
+ NotSignInException Http Status Code를 404에서 401로 변경

Auth - CORS 설정 추가 및 Header 에서 Token 확인 추가

---

.github/workflows/application.yml

+ github actions yml 파일 수정
***
+ 230810
***
+ test/resources/application.yml 파일 관련 설정 추가
+ bastion에서 was로 접속하는 script 추가

github actions yml 파일 수정

---

.github/workflows/application.yml

+ gradle 버전 설정 변경
***
+ 230810
***
+ test 관련 github action 오류 발생
+ 호환되지 않는 gradle 기능이 있어서 생기는 오류인 듯 함
+ 해결방법 1: 모든 버전 허용 (gradle(default) -> IntelliJ IDEA)
+ .idea 파일이 push 되지 않아 아마 실패할 듯..

gradle 버전 설정 변경

---

build.gradle

+ test build 제외 설정 추가
***
+ 230810
***
+ test build 제외

test build 제외 설정 추가

---

build.gradle

+ test build 제외 코드 수정
***
+ 230810
***
+ 수정

test build 제외 코드 수정

---

.github/workflows/application.yml

+ docker 배포 관련 설정 수정
***
+ 230810
***
+ docker build 및 push 경로 수정

docker 배포 관련 설정 수정`

---

.github/workflows/application.yml

+ ssh remote 관련 설정 수정
***
+ 230810
***
+ executing remote ssh commands using password에서 오류가 발생해 수정
+ 도커 경로가 잘못 설정되어 있어 수정
+ bastion에서 was로 접속하는 과정에서 오류 발생했을 수 있음

ssh remote

---

.github/workflows/application.yml

+ ip수정, script수정
***
+ 230810
***
+ bastion, was ip를 잘못 설정해줘서 secret 값 변경
+ script에서 was로 접속하는 명령어 수정

ip수정, script수정

---

.github/workflows/application.yml

+ ssh 접속 권한 부여
***
+ 230810
***
+ authentication 에러가 떠서 chmod command 추가

ssh 접속 권한 부여

---

.github/workflows/application.yml

+ github action 테스트용 커밋
***
+ 230810
***
+ secret의 PEM KEY 값 변경
+ cicd 테스트용 커밋

github action 테스트용 커밋

---

.github/workflows/application.yml

+ 에러 원인 파악을 위한 was 접속 command 삭제
***
+ 230810
***
+ chmod에서 권한 부여가 안 된 것인지, ssh 접속이 안 되는 것인지 확인 위함

에러 원인 파악을 위한 was 접속 command 삭제

---

.github/workflows/application.yml

+ was 접속 command 수정하여 다시 추가
***
+ 230810
***
+ 바보같이 명령어를 잘못 썼어..

was 접속 command 수정하여 다시 추가

---

.github/workflows/application.yml

+ sudo docker, ssh was 접속 script 수정
***
+ 230810
***
+ TTY 오류 해결을 위한 script 수정
+ sudo docker 관련 에러 수정

sudo docker, ssh was 접속 script 수정

---

.gitignore
src/main/java/com/service/releasenote/domain/company/dao/CompanyRepository.java
src/test/java/com/service/releasenote/IntegrationTest.java

+ 통합 테스트
***
+ 23.08.10
***
+ 통합테스트 수행
+ cicd 설정 관련 수정

통합 테스트 - cicd 설정 관련 수정

---

src/main/java/com/service/releasenote/domain/company/application/CompanyService.java
src/main/java/com/service/releasenote/global/config/KICConfig.java
src/main/java/com/service/releasenote/global/config/S3Config.java
src/main/java/com/service/releasenote/global/constants/KICConstants.java
src/main/java/com/service/releasenote/global/constants/S3Constants.java

[ADD] kic 오브젝트 스토리지 변경
***
23.08.10
***
드디어 해냈습니다 제가!! KIC 오브젝트 스토리지!! 칭찬해주세요!!!!!

[ADD] kic 오브젝트 스토리지 변경

---

.github/workflows/application.yml

+ key.yml 관련 설정 추가
***
+ 230810
***
+ key 파일 생성 및 secret 키 추가

key.yml 관련 설정 추가

---

src/test/java/com/service/releasenote/IntegrationTest.java

+ [ADD] 통합 테스트 cicd
***
+ 23.08.10
***
+ 통합 테스트 cicd 
+ 잘 됐으면 좋겠어요

통합 테스트 cicd

---

src/test/java/com/service/releasenote/IntegrationTest.java

+ 통합 테스트 cicd
***
+ 23.08.10
***
+ 제발

[ADD] 통합 테스트 cicd

---

.github/workflows/application.yml

+ github action 확인용
***
+ 230810
***
+ main 되는지 확인..

github action 확인용

---

build.gradle
src/test/resources/application.yml

+ test build 제외 삭제
***
+ 230810
***
+ test..

test build 제외 삭제

---

.github/workflows/application.yml
build.gradle

+ 사용하지 않는 이미지 삭제
***
+ 230810
***
+ build.gradle에서 test 무시 옵션 활성화
+ docker에서 불필요한 image 삭제하는 command 숙제

사용하지 않는 이미지 삭제

---

.github/workflows/application.yml

+ image prune
***
+ 230810
***
+ 사용하지 않는 image 삭제 커맨드가 안 먹어서 prune으로 변경

[REFACTOR]image prune

---

build.gradle

+ [DELETE]test build에서 제외 코드 삭제
***
+ 230810
***
+ test build에서 제외 코드 삭제
+ image 삭제 커맨드가 안 먹음..

[DELETE]test build에서 제외 코드 삭제

---

.github/workflows/application.yml

+ github action 테스트용
***
+ 230810
***
+ test application.yml에서 mysql을 localhost에서 was private IP로 변경 테스트

github action 테스트용

---

.github/workflows/application.yml

+ mysql 설정 추가
***
+ 230810
***
+ test를 위한 mysql 설정 추가

[ADD]mysql 설정 추가

---

.github/workflows/application.yml

+ quatation추가
***
+ 230810
***
+ mysql 세팅 수정

[REFACTOR]quatation추가

---

.github/workflows/application.yml

+ mysql password 설정 변경
***
+ 230810
***
+ password secret으로 변경

[REFACTOR]mysql password 설정 변경

---

.github/workflows/application.yml

+ mysql port 추가
***
+ 230810
***
+ mysql port 추가

[ADD]mysql port 추가

---

.github/workflows/application.yml

+ mysql setup 변경
***
+ 230810
***
+ 아예 다른 내용으로 변경

[REFACTOR]mysql setup 변경

---

.github/workflows/application.yml
build.gradle

+ build.gradle 테스트 관련 설정 변경
***
+ 230810
***
+ build.gradle 테스트 관련 설정 변경

[REFACTOR]build.gradle 테스트 관련 설정 변경

---

.github/workflows/application.yml

+ mysql user 수정
***
+ 230811
***
+ 혹시나해서..

[REFACTOR]mysql user 수정

---

.github/workflows/application.yml

+ test application.yml 파일 생성 삭제
***
+ 230811
***
+ 제발..

[DELETE]test application.yml 파일 생성 삭제

---

build.gradle

+ junit, mockito 의존성 추가
***
+ 230811
***
+ dd

[ADD]junit, mockito 의존성 추가

---

build.gradle

+ mockito 의존성 삭제
***
+ 230811
***

[DELETE]mockito 의존성 삭제

---

src/test/java/com/service/releasenote/IntegrationTest.java
src/test/java/com/service/releasenote/alarm/AlarmControllerTest.java
src/test/java/com/service/releasenote/alarm/AlarmServiceTest.java
src/test/java/com/service/releasenote/auth/AuthControllerTest.java
src/test/java/com/service/releasenote/auth/AuthServiceTest.java
src/test/java/com/service/releasenote/category/CategoryControllerTest.java
src/test/java/com/service/releasenote/category/CategoryServiceTest.java
src/test/java/com/service/releasenote/memberProject/memberProjectControllerTest.java
src/test/java/com/service/releasenote/memberProject/memberProjectServiceTest.java
src/test/java/com/service/releasenote/project/ProjectControllerTest.java
src/test/java/com/service/releasenote/project/ProjectServiceTest.java

+ 테스트 프로파일 일괄 적용, 통합 테스트 시나리오 완료
***
+ 23.08.11
***
+ 테스트 프로파일 일괄 적용, 통합 테스트 시나리오 완료

테스트 프로파일 일괄 적용, 통합 테스트 시나리오 완료

---

src/test/java/com/service/releasenote/ReleaseBackendApplicationTests.java

+ 타이틀을 작성해주세요
***
+ YY.MM.DD
***

[ADD] 테스트 프로파일 일괄 적용

---

.github/workflows/application.yml

+ RabbitMQ 설치 설정 추가
***
+ 230811
***

[ADD]RabbitMQ 설치 설정 추가

---

.github/workflows/application.yml

+ 타이틀을 작성해주세요
***
+ YY.MM.DD
***

[DELETE]image prune 설 정 삭제

---

.github/workflows/application.yml

+ 타이틀을 작성해주세요
***
+ YY.MM.DD
***

[DELETE]push 삭제

---

.github/workflows/application.yml

+ was2에 이미지 pull step 변경
***
+ 230811
***
+ was2

[REFACTOR]was2에 이미지 pull step 변경

---

.github/workflows/application.yml

+ container name 변경
***
+ 230811
***
+ was1과 Was2 각각 doklib_was1, doklib_was2로 변경

[REFACTOR]container name 변경

---

.github/workflows/application.yml

+ container name 수정
***
+ 230811
***

[REFACTOR]container name 수정

---

.github/workflows/application.yml

+ 8080포트 사용중 에러 확인
***
+ 230811
***
+ 갑자기 8080 포트를 이미 사용중이라는 에러가 떠서 확인용

8080포트 사용중 에러 확인

---

.github/workflows/application.yml

+ was2 삭제하는 컨테이너 이름 오타
***
+ 230811
***

[REFACTOR]was2 삭제하는 컨테이너 이름 오타

---

src/main/java/com/service/releasenote/global/config/WebConfig.java

+ WebConfig 에 ILB 주소 추가
***
+ 23.08.12
***
+ WebConfig 에 ILB 주소 추가

[REFACTOR] WebConfig 에 ILB 주소 추가

---

.github/workflows/application.yml

+ 시크릿 키 이름 수정
***
+ 230813
***
+ 이름이 명확하지 않아서 일괄 수정

[REFACTOR]시크릿 키 이름 수정

---

src/main/java/com/service/releasenote/global/config/WebConfig.java

+ WebConfig 에 ILB 주소 추가 - test
***
+ 23.08.14
***
+ WebConfig 에 ILB 주소 추가 - test

[REFACTOR] WebConfig 에 ILB 주소 추가 - test

---

src/main/java/com/service/releasenote/global/config/WebConfig.java

+ 타이틀을 작성해주세요
***
+ YY.MM.DD
***

[REFACTOR] WebConfig 에 ELB 주소 추가

---

src/main/java/com/service/releasenote/global/config/WebConfig.java

+ 타이틀을 작성해주세요
***
+ YY.MM.DD
***

[REFACTOR] WebConfig 에 ILB-public 주소 추가

---

src/main/java/com/service/releasenote/global/config/SecurityConfig.java

+ 타이틀을 작성해주세요
***
+ YY.MM.DD
***

[REFACTOR] /favicon.ico 추가

---

src/main/java/com/service/releasenote/domain/project/api/ProjectController.java

+ redis 연결 완
***
+ 230815
***
+ 도커의 redis 포트를 0.0.0.0:6379->6379/tcp 로 바꿈
+ 기존: 6379/tcp

redis 연결 완

---

src/main/java/com/service/releasenote/domain/alarm/api/AlarmController.java
src/main/java/com/service/releasenote/domain/category/api/CategoryController.java
src/main/java/com/service/releasenote/domain/company/api/CompanyController.java
src/main/java/com/service/releasenote/domain/member/api/AuthController.java
src/main/java/com/service/releasenote/domain/member/api/MemberCompanyController.java
src/main/java/com/service/releasenote/domain/member/api/MemberProjectController.java
src/main/java/com/service/releasenote/domain/project/api/ProjectController.java
src/main/java/com/service/releasenote/domain/release/api/ReleaseController.java

+ api 경로 수정
***
+ 230815
***
+ 모든 경로 앞에 /api 추가

[REFACTOR]api 경로 수정

---

src/test/java/com/service/releasenote/IntegrationTest.java
src/test/java/com/service/releasenote/alarm/AlarmControllerTest.java
src/test/java/com/service/releasenote/auth/AuthControllerTest.java
src/test/java/com/service/releasenote/category/CategoryControllerTest.java
src/test/java/com/service/releasenote/memberProject/memberProjectControllerTest.java
src/test/java/com/service/releasenote/project/ProjectControllerTest.java
src/test/java/com/service/releasenote/releases/ReleaseControllerTest.java

+ test api 경로 수정
***
+ 230815
***
+ Test api 경로 수정
+ 멤버 빌드 isDeleted 추가

[REFACTOR]test api 경로 수정

---

src/main/java/com/service/releasenote/global/config/SecurityConfig.java

+ security config 수정
***
+ 230815
***
+

[REFACTOR]security config 수정

---

.github/workflows/application.yml

+ 사용하지 않는 이미지 삭제 명령어 추가
***
+ 230815
***
+ docker image prune
+ y

[ADD]사용하지 않는 이미지 삭제 명령어 추가

---

src/test/java/com/service/releasenote/IntegrationTest.java

+ 통합 테스트 누락된 commit
***
+ 23.08.15
***
+ 대한 독립 만세

통합 테스트 누락된 commit

---

.github/workflows/application.yml

+ redis 인스턴스 생성 테스트
***
+ 230815
***
+ redis가 localhost:6379로 연결 안 되는 문제
+ redis를 새로운 인스턴스에 생성

redis 인스턴스 생성 테스트

---

src/main/java/com/service/releasenote/global/alarm/api/RabbitmqAdminController.java
src/main/java/com/service/releasenote/global/alarm/application/RabbitmqAdminService.java
src/main/java/com/service/releasenote/global/alarm/dto/RabbitmqAdminDto.java

+ [ADD] 어드민용 exchange 생성 api
***
+ 23.08.16
***
+ [ADD] 어드민용 exchange 생성 api

[ADD] 어드민용 exchange 생성 api

---

src/main/java/com/service/releasenote/domain/release/api/ReleaseController.java
src/main/java/com/service/releasenote/domain/release/application/ReleaseService.java

[REFACTOR] addRelease 반환 데이터 수정
***
23.08.16
***
addRelease 반환 데이터 id에서 dto로 바꿨습니다

[REFACTOR] addRelease 반환 데이터 수정

---

src/main/java/com/service/releasenote/domain/release/application/ReleaseService.java
src/test/java/com/service/releasenote/releases/ReleaseControllerTest.java
src/test/java/com/service/releasenote/releases/ReleaseServiceTest.java

+ [HOTFIX] api 변경에 따른 테스트 실패 수정
***
+ 23.08.16
***
+ 릴리즈 api 변경에 따른 테스트 실패 수정

[HOTFIX] api 변경에 따른 테스트 실패 수정

---

src/main/java/com/service/releasenote/domain/project/api/ProjectController.java
src/main/java/com/service/releasenote/domain/project/application/ProjectService.java
src/main/java/com/service/releasenote/domain/project/dao/ProjectCustomRepository.java
src/main/java/com/service/releasenote/domain/project/dao/ProjectRepositoryImpl.java

+ 특정 회사 내에서 내 프로젝트 찾기 api 추가
***
+ 23.08.16
***
+ 기존에 내가 속한 프로젝트 api와 유사하게, 특정 회사에서 내가 속한 프로젝트만을 반환해주는 api 작성

[ADD] 특정 회사 내에서 내 프로젝트 찾기 api 추가

---

src/main/java/com/service/releasenote/domain/project/api/ProjectController.java
src/main/java/com/service/releasenote/domain/project/application/ProjectService.java
src/main/java/com/service/releasenote/domain/project/dao/ProjectCustomRepository.java
src/main/java/com/service/releasenote/domain/project/dao/ProjectRepositoryImpl.java

+ 타이틀을 작성해주세요
***
+ YY.MM.DD
***

[ADD] 특정 회사 내에서 내 프로젝트 찾기 api 추가 - 오류 수정

---

src/main/java/com/service/releasenote/domain/project/dao/ProjectRepositoryImpl.java

+ 타이틀을 작성해주세요
***
+ YY.MM.DD
***

[ADD] 특정 회사 내에서 내 프로젝트 찾기 api 추가 - 오류 수정 2

---

src/main/java/com/service/releasenote/domain/alarm/api/AlarmController.java
src/main/java/com/service/releasenote/domain/alarm/application/AlarmService.java
src/main/java/com/service/releasenote/domain/alarm/dao/AlarmCustomRepository.java
src/main/java/com/service/releasenote/domain/alarm/dao/AlarmRepository.java
src/main/java/com/service/releasenote/domain/alarm/dao/AlarmRepositoryImpl.java
src/main/java/com/service/releasenote/domain/member/api/MemberCompanyController.java
src/main/java/com/service/releasenote/domain/member/dto/MemberCompanyDTO.java

+ [ADD] 내 알람 조회 api 
***
+ 23.08.17
***
+  내 알람 조회 api

[ADD] 내 알람 조회 api 

---

src/main/java/com/service/releasenote/domain/category/api/CategoryController.java
src/main/java/com/service/releasenote/domain/category/application/CategoryService.java
src/main/java/com/service/releasenote/global/constants/KICConstants.java

[ADD] 카테고리 이미지 업로드 기능 추가
***
23.08.17
***
카테고리 컨트롤러에 오브젝트 스토리지 이미지 업로드 기능 추가했습니다

[ADD] 카테고리 이미지 업로드 기능 추가

---

src/main/java/com/service/releasenote/global/config/SecurityConfig.java

+ [ADD] 카테고리 조회 보안설정 수정
***
+ 23.08.17
***
+ 카테고리 조회 보안설정 수정 - get 허용

[ADD] 카테고리 조회 보안설정 수정

---

src/main/java/com/service/releasenote/domain/release/application/ReleaseService.java
src/test/java/com/service/releasenote/releases/ReleaseServiceTest.java

+ [ADD] 카테고리 생성 시 수정자 이메일 추가
***
+ 23.08.17
***
+ 카테고리 생성 시 수정자 이메일 추가

[ADD] 카테고리 생성 시 수정자 이메일 추가

---

src/main/java/com/service/releasenote/domain/category/application/CategoryService.java
src/main/java/com/service/releasenote/domain/company/application/CompanyService.java
src/main/java/com/service/releasenote/global/config/KICConfig.java
src/main/java/com/service/releasenote/global/config/S3Config.java
src/main/java/com/service/releasenote/global/constants/KICConstants.java
src/main/java/com/service/releasenote/global/constants/S3Constants.java

[REFACTOR] S3로 오브젝트 스토리지 수정
***
23.08.22
***
KIC에서 S3로 오브젝트 스토리지 수정

[REFACTOR] S3로 오브젝트 스토리지 수정

---

src/main/java/com/service/releasenote/global/config/S3Config.java
src/main/java/com/service/releasenote/global/constants/S3Constants.java

[REFACTOR] 이미지 삭제 추가 수정 필요 (API키 수정 - 재발급 필요)
***
23.08.22
***
추가로 수정해야 합니다..! API 키가 막혀서 나중에 다시 수정해야 할듯요. 지금 업로드는 되는데 삭제가 안 되는 것임!

[REFACTOR] 이미지 삭제 추가 수정 필요 (API키 수정 - 재발급 필요)
